### ISSUE TITLE
Links to chapters with special characters are not rendered

### ISSUE THREAD

**Issue by JanoschDeurer** [orzih/mkdocs-with-pdf#20]
Links that include special characters like ä or & are not resolved in the pdf. On rendering the pdf the following error is thrown:
```
No anchor #broken_entry_&/ for internal URI reference
```
This also effects the links in the toc as mentioned in #15 

I created a minimal example with the bug:
[mkdocs_heading_example.zip](https://github.com/orzih/mkdocs-with-pdf/files/5255664/mkdocs_heading_example.zip)

**Comment by orzih** [comment]
Thank you for attaching the sample.
It fixed in v0.7.2, please check it.

**Comment by orzih** [comment]
... not fixed.
https://discussions.apple.com/thread/251041261

**Comment by JanoschDeurer** [comment]
Thanks for the fast response again :). I updated my version to mkdocs-with-pdf-0.7.2 from pip. However, I can not see any difference in my example pdf. The links still do not work, interestingly thou the errors are no longer thrown while creating the pdf.

**Comment by orzih** [comment]
Many PDF viewers don't seem to support percent encoding. Is it a PDF specification?

I tried replacing all '%' to '-' in anchors id and links href.
It's easily, but I think there's probably no duplication.

**Comment by JanoschDeurer** [comment]
Great :) The links with special characters are working now :+1: Thank you so much :)
